### ISSUE TITLE
waitForTrigger

### ISSUE THREAD

**Issue by 3rror404** [twanlass/tour.js#1]
Could you please provide an example of how to use `waitForTrigger`? 

For example, I would like the tour to pause until the user has finished entering text in to an input (`#input1`). Then guide them to use another input (`#input2`). How would this be done?

Many thanks.

**Comment by twanlass** [comment]
Right now it's designed for work on a click event. So for example, you'd pass in a css selector (#some_id or .some_class) and when this selector is clicked TourJS will automatically resume the tour and progress to the next step. 

It sounds like you're looking for something like an onBlur event though (i.e. user switches away from input1 then continue the tour). 

One 'hack' you could try:
1. Pass in #input2 as the selector waitForTrigger
2. Set an onBlur event handler for #input1. onBlur, do something like $('#input2').click() 

This would then trigger the tour to continue. 

Cheers,

-t

**Comment by 3rror404** [comment]
Thanks twanlass. I got this working using something similar to your suggestion.
